<Project>
    <!-- Build configurations -->
  <PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
    <SignAssembly>True</SignAssembly>
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>catsarmy.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>catsarmy</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>$(AndroidSigningPassFile)</AndroidSigningKeyPass>
    <AndroidSigningStorePass>$(AndroidSigningPassFile)</AndroidSigningStorePass>
  </PropertyGroup>
</Project>