<Project>
    <!-- Build configurations -->
    <!--<PropertyGroup>
        <AssemblyOriginatorKeyFile>E:\Source\repos\School\Android\Material-You-Chess\com.catsarmy.chess.keystore</AssemblyOriginatorKeyFile>
        <AndroidSigningKeyStore>com.catsarmy.chess.keystore</AndroidSigningKeyStore>
        <AndroidSigningKeyAlias>com.catsarmy.chess</AndroidSigningKeyAlias>
        <AndroidSigningKeyPass>gilaoded</AndroidSigningKeyPass>
        <AndroidSigningStorePass>gilaoded</AndroidSigningStorePass>
    </PropertyGroup>-->
</Project>