<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>$(MSBuildProjectName.Replace(" ", "-"))</AssemblyName>
    <TargetFramework>net10.0-android36.0</TargetFramework>
    <SupportedOSPlatformVersion>33.0</SupportedOSPlatformVersion>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "."))</RootNamespace>
    <RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
    <DisableMauiImplicitPackageReferences>True</DisableMauiImplicitPackageReferences>
    <ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationId>com.catsarmy.chess</ApplicationId>
  </PropertyGroup>

  <PropertyGroup>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>preview-recommended</AnalysisLevel>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);syslib1031</NoWarn>
  </PropertyGroup>
  
  <Import Project="Properties\Material-You-Chess.Build.props.user" />
  
  <ItemGroup>
    <None Remove="ic_launcher-playstore.png" />
    <None Remove="play_graphic.png" />
  </ItemGroup>
  
  <ItemGroup>
    <GoogleServicesJson Include="$(GoogleServicesJsonFile)" />
    <None Include="Properties\Material-You-Chess.Build.props.user" />
    <None Include="Properties\Material-You-Chess.Build.props.user.template" />
  </ItemGroup>

  <PropertyGroup>
    <RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10/nuget/v3/index.json</RestoreAdditionalProjectSources>
    <RestoreAdditionalProjectSources>$(SolutionDir)/BindingPackages/Release</RestoreAdditionalProjectSources>
    <AndroidFragmentType>AndroidX.Fragment.App.Fragment</AndroidFragmentType>
    <AndroidEnableMarshalMethods>True</AndroidEnableMarshalMethods>
    <AndroidEnablePreloadAssemblies>True</AndroidEnablePreloadAssemblies>
    <!--<JavaMaximumHeapSize>2G</JavaMaximumHeapSize>-->
  </PropertyGroup>

  <PropertyGroup>
    <SignAssembly>True</SignAssembly>
    <AndroidUseApkSigner>True</AndroidUseApkSigner>
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>catsarmy.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>catsarmy</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>$(AndroidSigningPassword)</AndroidSigningKeyPass>
    <AndroidSigningStorePass>$(AndroidSigningPassword)</AndroidSigningStorePass>  
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <RestoreAdditionalProjectSources>$(SolutionDir)/BindingPackages/Debug</RestoreAdditionalProjectSources>
    <RunAOTCompilation>False</RunAOTCompilation>
    <PublishTrimmed>False</PublishTrimmed>
    <Optimize>False</Optimize>
    <StripSymbols>False</StripSymbols>
    <DebugSymbols>True</DebugSymbols>
    <DebugType>full</DebugType>
    <DebugType>embedded</DebugType>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
    <AndroidManagedSymbols>True</AndroidManagedSymbols>
    <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <RunAOTCompilation>True</RunAOTCompilation>
    <IsAotCompatible>True</IsAotCompatible>
    <DebugType>portable</DebugType>
      <!--
        Enables trim analyzers and full trimming during Release mode.
        To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
      -->
    <TrimMode>full</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseUI" Version="1.0.0" />

    <PackageReference Include="Microsoft.Maui.Graphics" Version="10.0.0-preview.3.25208.1" />
    <PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.0-preview.3.25208.1" />
    <PackageReference Include="System.Text.Json" Version="10.0.0-preview.3.25171.5" />

    <PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.9.1.3" />
    <PackageReference Include="Xamarin.AndroidX.Annotation.Jvm" Version="1.9.1.3" />
    <PackageReference Include="Xamarin.AndroidX.Core.Animation" Version="1.0.0.24-alpha02" />

    <PackageReference Include="Xamarin.Firebase.AppCheck" Version="118.0.0.5" />
    <PackageReference Include="Xamarin.Firebase.AppCheck.Debug" Version="118.0.0.5" />
    <PackageReference Include="Xamarin.Firebase.AppCheck.PlayIntegrity" Version="118.0.0.5" />
    <PackageReference Include="Xamarin.Firebase.Auth" Version="123.2.0.1" />
    <PackageReference Include="Xamarin.Firebase.Storage" Version="121.0.1.3" />

    <PackageReference Include="Xamarin.Android.Glide" Version="4.16.0.12" />
    <PackageReference Include="Xamarin.Android.Glide.AVIF.Integration" Version="4.16.0.12" />
    <PackageReference Include="Xamarin.Android.Glide.RecyclerViewIntegration" Version="4.16.0.12" />
    
    <PackageReference Include="Xamarin.AndroidX.Activity" Version="1.10.1.1" />
    <PackageReference Include="Xamarin.AndroidX.Fragment" Version="1.8.6.1" />

    <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.8.0.9" />
    <PackageReference Include="Xamarin.AndroidX.CardView" Version="1.0.0.34" />
    <PackageReference Include="Xamarin.AndroidX.ConstraintLayout" Version="2.2.1.1" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0.32" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Extensions" Version="2.2.0.32" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.13.0.0-alpha12" />
   
    <PackageReference Include="Xamarin.GooglePlayServices.Auth" Version="121.3.0.2" />
    <PackageReference Include="Xamarin.KotlinX.Coroutines.Android" Version="1.9.0.3" />
    <PackageReference Include="Xamarin.AndroidX.Core.Core.Ktx" Version="1.16.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Ktx" Version="2.8.7.3" />
    <PackageReference Include="Xamarin.GoogleAndroid.Libraries.Identity.GoogleId" Version="1.1.0.9" />
    <PackageReference Include="Xamarin.AndroidX.RecyclerView" Version="1.4.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.8.7.3" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" Version="2.8.7.3" />

    <PackageReference Include="Xamarin.Google.Android.Recaptcha" Version="18.7.0.1" />
    <PackageReference Include="Xamarin.GooglePlayServices.Nearby" Version="119.3.0.5" />
  </ItemGroup>
</Project>
