<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Chess</RootNamespace>
    <TargetFramework>net9.0-android35.0</TargetFramework>
    <SupportedOSPlatformVersion>32.0</SupportedOSPlatformVersion>
    <RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
    <ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationId>com.catsarmy.chess</ApplicationId>
   
    <!--<ApplicationDisplayVersion>$(Major).$(Minor).$(Patch)</ApplicationDisplayVersion>
    <ApplicationVersion>$(Major)</ApplicationVersion>
    <ApplicationId>com.catsarmy.chess</ApplicationId>
    <Version>$(ApplicationDisplayVersion).$(Build)</Version>
    <Major>1</Major>
    <Minor>0</Minor>
    <Patch>0</Patch>
    <Build>0</Build>-->
  </PropertyGroup>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AnalysisLevel>preview</AnalysisLevel>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <WarningLevel>9999</WarningLevel>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  
  <Import Project="Properties\Material-You-Chess.Build.props.user" />
  
  <ItemGroup>
    <GoogleServicesJson Include="$(GoogleServicesJsonFile)" />
    <None Include="Properties\Material-You-Chess.Build.props.user" />
    <None Include="Properties\Material-You-Chess.Build.props.user.template" />
  </ItemGroup>

  <PropertyGroup>
    <EnableLLVM>False</EnableLLVM>
    <AndroidEnableProfiler>False</AndroidEnableProfiler>
    <AndroidEnableMultiDex>False</AndroidEnableMultiDex>
    <AndroidEnableProfiledAot>False</AndroidEnableProfiledAot>
    <AndroidFragmentType>AndroidX.Fragment.App.Fragment</AndroidFragmentType>
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
    <!--<AndroidEnableMarshalMethods>True</AndroidEnableMarshalMethods>
    <AndroidGenerateJniMarshalMethods>True</AndroidGenerateJniMarshalMethods>
    <AndroidEnablePreloadAssemblies>True</AndroidEnablePreloadAssemblies>
    <AndroidLintEnabled>True</AndroidLintEnabled>-->
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugSymbols>True</DebugSymbols>
    <DebugType>full</DebugType>
    <DebugType>embedded</DebugType>
    <AndroidManagedSymbols>True</AndroidManagedSymbols>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
    <Optimize>False</Optimize>
    <StripSymbols>False</StripSymbols>
    <RunAOTCompilation>False</RunAOTCompilation>
    <PublishTrimmed>False</PublishTrimmed>
    <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">        
  <RunAOTCompilation>True</RunAOTCompilation>
  <IsAotCompatible>True</IsAotCompatible>
  <DebugType>portable</DebugType>
    <!--
      Enables trim analyzers and full trimming during Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
  <TrimMode>full</TrimMode>

  <SignAssembly>True</SignAssembly>
  <AndroidUseApkSigner>true</AndroidUseApkSigner>
  <AndroidKeyStore>true</AndroidKeyStore>
  <AndroidSigningKeyStore>catsarmy.keystore</AndroidSigningKeyStore>
  <AndroidSigningKeyAlias>catsarmy</AndroidSigningKeyAlias>
  <AndroidSigningKeyPass>gilaoded</AndroidSigningKeyPass>
  <AndroidSigningStorePass>gilaoded</AndroidSigningStorePass>  
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Graphics" Version="9.0.40" />
    <PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.40" />
    <PackageReference Include="System.Text.Json" Version="9.0.3" />

<!--    <PackageReference Include="Xamarin.Android.Glide" Version="4.16.0.11" />
    <PackageReference Include="Xamarin.Android.Glide.Annotations" Version="4.16.0.11" />
    <PackageReference Include="Xamarin.Android.Glide.DiskLruCache" Version="4.16.0.11" />
    <PackageReference Include="Xamarin.Android.Glide.GifDecoder" Version="4.16.0.11" />
    <PackageReference Include="Xamarin.Android.Glide.RecyclerViewIntegration" Version="4.16.0.11" />-->

    <PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.9.1.2" />
    <PackageReference Include="Xamarin.AndroidX.Annotation.Jvm" Version="1.9.1.2" />

<!--    <PackageReference Include="Xamarin.AndroidX.DataBinding.ViewBinding" Version="8.8.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" Version="2.8.7.2" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.8.7.2" />-->
    <!--<PackageReference Include="Xamarin.AndroidX.ConstraintLayout" Version="2.2.1" />-->
    <!--<PackageReference Include="Xamarin.AndroidX.Navigation.UI" Version="2.8.5.1" />-->
    <!--<PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.0.5" />-->
    <!--<PackageReference Include="Xamarin.AndroidX.Biometric" Version="1.1.0.27" />-->
    <!--<PackageReference Include="Xamarin.AndroidX.Media" Version="1.7.0.9" />-->
    
    <!--<PackageReference Include="Xamarin.AndroidX.Compose.UI.ViewBinding" Version="1.7.6.1" />
    <PackageReference Include="Xamarin.AndroidX.Compose.Material.Icons.Extended" Version="1.7.6.1" />
    <PackageReference Include="Xamarin.AndroidX.Compose.Material3" Version="1.3.1.2" />
    <PackageReference Include="Xamarin.AndroidX.Compose.Material" Version="1.7.6.1" />-->

    <PackageReference Include="Xamarin.Firebase.AppCheck" Version="118.0.0.4" />
<!--    <PackageReference Include="Xamarin.Firebase.Database" Version="121.0.0.4" />
    <PackageReference Include="Xamarin.Firebase.Firestore" Version="125.0.0.1" />-->

    <!--<PackageReference Include="Xamarin.Firebase.Auth" Version="122.3.1.4" />-->
    <!--<PackageReference Include="Xamarin.Firebase.Storage" Version="121.0.1.2" />-->

    <!--<PackageReference Include="Xamarin.AndroidX.Credentials.PlayServicesAuth" Version="1.2.2.4" />
    <PackageReference Include="Xamarin.GoogleAndroid.Libraries.Identity.GoogleId" Version="1.1.0.6" />
    <PackageReference Include="Xamarin.GooglePlayServices.Identity" Version="118.1.0.4" />-->

    <PackageReference Include="Xamarin.Google.Android.Recaptcha" Version="18.7.0" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.12.0.2" />
    <PackageReference Include="Xamarin.GooglePlayServices.Nearby" Version="119.3.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FirebaseUI\FirebaseUI\FirebaseUI.csproj" />
  </ItemGroup>
</Project>
